export default {
    absensi: require('../img/absensi.png'),
    bootstraplogo: require ('../img/bootstraplogo.png'),
    dicodingawscloud: require ('../img/cloudpractitioneressentials.jpg'),
    css3logo: require ('../img/css3logo.png'),
    cucumberlogo: require ('../img/cucumberlogo.png'),
    demoblazetesting: require ('../img/demoblazetesting.png'),
    figmalogo: require ('../img/figmalogo.png'),
    googledigiralmarketingcertificate: require ('../img/fundamentaldigitalmarketing.jpg'),
    html5logo: require ('../img/html5logo.png'),
    javalogo: require ('../img/javalogo.png'),
    javascriptlogo: require ('../img/javascriptlogo.jpg'),
    postmantlogo: require ('../img/postmantlogo.png'),

    owntols: require ('../img/owntols.png'),
    nubie: require ('../img/nubie.png'),
    sistempengarsipan: require ('../img/pengarsipan.png'),

    photoshoplogo: require ('../img/photoshoplogo.png'),
    pythonlogo: require ('../img/pythonlogo.png'),
    flutterlogo: require ('../img/flutterlogo.png'),
    phplogo: require ('../img/phplogo.png'),
    seleniumlogo: require ('../img/seleniumlogo.png'),
    cypresslogo: require('../img/cypresslogo.png'),
    webdriveriologo: require('../img/webdriveriologo.png'),
    tailwindcsslogo: require ('../img/tailwindcsslogo.svg'),
    testnglogo: require ('../img/testnglogo.png'),
    theinternettesting: require ('../img/theinternettesting.png'),
    wordpresslogo: require ('../img/wordpresslogo.svg'),
}
