export default {
    absensi: require('../img/absensi.png').default,
    bootstraplogo: require ('../img/bootstraplogo.png').default,
    dicodingawscloud: require ('../img/cloudpractitioneressentials.jpg').default,
    css3logo: require ('../img/css3logo.png').default,
    cucumberlogo: require ('../img/cucumberlogo.png').default,
    demoblazetesting: require ('../img/demoblazetesting.png').default,
    figmalogo: require ('../img/figmalogo.png').default,
    googledigiralmarketingcertificate: require ('../img/fundamentaldigitalmarketing.jpg').default,
    html5logo: require ('../img/html5logo.png').default,
    javalogo: require ('../img/javalogo.png').default,
    javascriptlogo: require ('../img/javascriptlogo.jpg').default,
    postmantlogo: require ('../img/postmantlogo.png').default,

    owntols: require ('../img/owntols.png').default,
    nubie: require ('../img/nubie.png').default,
    sistempengarsipan: require ('../img/pengarsipan.png').default,

    photoshoplogo: require ('../img/photoshoplogo.png').default,
    pythonlogo: require ('../img/pythonlogo.png').default,
    flutterlogo: require ('../img/flutterlogo.png').default,
    phplogo: require ('../img/phplogo.png').default,
    seleniumlogo: require ('../img/seleniumlogo.png').default,
    cypresslogo: require('../img/cypresslogo.png').default,
    webdriveriologo: require('../img/webdriveriologo.png').default,
    tailwindcsslogo: require ('../img/tailwindcsslogo.svg').default,
    testnglogo: require ('../img/testnglogo.png').default,
    theinternettesting: require ('../img/theinternettesting.png').default,
    wordpresslogo: require ('../img/wordpresslogo.svg').default,
}
